#!/usr/bin/php
<?php

require __DIR__ . '/../../vendor/autoload.php';

$conf = array(
    'excludeTests' => false,
    'codingStandard' => 'PSR2',
    'messRules' => 'controversial'
);

$files = Project\Util\GitUtil::getCommitedFiles();
$console = new Project\Tool\CodeQualityTool($files, $conf);
$console->run();
