#!/usr/bin/php
<?php

require __DIR__ . '/../../vendor/autoload.php';

$conf = array(
    'excludeTests' => false,
    'codingStandard' => array('PSR2'),
    'messRules' => 'controversial',
    'customChecks' => array(), // i.e. scss-lint, jscs --preset=jquery
);

$files = Project\Util\GitUtil::getCommitedFiles();
$console = new Project\Tool\CodeQualityTool($files, $conf);
$console->run();
